// LonginesMaster2020/src/components/TheCover.vue
<template>
  <div class="the-cover" :style="{ height: `${$root.wh}px` }">
    <div class="the-cover__container">
      <h1>
        <div>預約你的</div>
        <div>精彩時刻</div>
      </h1>
      <div class="the-cover__intro">
        <p>時間管理者，</p>
        <p>創造許多人生精彩，</p>
        <p>虛度光陰者，</p>
        <p>錯過豐富人生機會，</p>
        <p>這一刻，<br v-if="$root.breakpoints.md()" />你的選擇是？</p>
        <div class="mouse">
          <img src="../assets/icon/mouse.svg" alt="">
        </div>
      </div>
    </div>
    <div v-if="!$root.breakpoints.md()" class="the-cover__gradient" />
  </div>
</template>

<script>
export default {
  name: 'TheCover'
}
</script>

<style lang="stylus">
@import '../util/global.styl'

.the-cover
  position relative
  text-align center
  background-image url(../assets/cover.jpg)
  background-position center
  font-weight 300
  text-shadow: 0 2px 4px rgba(0, 0, 0, 0.5)
  background-repeat no-repeat
  background-size cover
  background-color #000
  @media (min-width $breakpoint-md)
    text-align left
  &__container
    position relative
    z-index 3
    height 100%
    @media (min-width $breakpoint-md)
      width 320px
      background-color rgba(0, 0, 0, 0.7)
      margin-left auto
    & > *
      position absolute
      left 50%
      transform translateX(-50%)
      box-sizing border-box
      width 100%
      @media (min-width $breakpoint-md)
        position static
        left auto
        transform none
  & h1
    letter-spacing 20px
    font-size 4.0rem
    line-height 1.25
    padding-left 20px
    padding-top 12.32vh
    @media (min-width $breakpoint-md)
      padding-left 0
      font-weight 100
      margin-bottom 18px
      top 15.85%
      padding-top 28.23vh
      letter-spacing 16px
      font-size 3.2rem
      line-height 1.56
      & > div
        &:first-child
          padding-left 44px
        &:last-child
          padding-left 94px
  &__intro
    font-size 2.0rem
    line-height 1.4
    letter-spacing 0.7px
    padding-left 0.7px
    bottom 3.7%
    @media (min-width $breakpoint-md)
      padding-left 94px
    & .mouse
      display flex
      justify-content center
      margin-top 8px
      position relative
      @media (min-width $breakpoint-md)
        position absolute
        margin-top 0
        left 45px
        top calc(28.23% + 118px)
      & img
        width 25px
        animation point-down 1.5s both infinite
        @media (min-width $breakpoint-md)
          width 18px
        @keyframes point-down
          0%
            transform translateY(0px)
          50%
            transform translateY(10px)
      &::after
        content ''
        display block
        position absolute
        width 1px
        background-color #fff
        height calc(3.7vh - 10px)
        top 75px
        @media (min-width $breakpoint-md)
          top 64px
          height calc(71.77vh - 182px)
  &__gradient
    position absolute
    bottom 0
    left 0
    width 100%
    height 38.91%
    background-image linear-gradient(to bottom, rgba(255, 255, 255, 0), #000000 55%)
</style>

// taiwan-social-worker/src/components/TheCover.svelte
<template>
  <div class="the-cover" id="the-cover">
    <div class="bg bg--cover" />
    <div class="bg bg--girl" />
    <img class="title" src={isDeskW ? titleDesk : titleMob } alt="">
    <div class="preface">
      <div class="preface__bg" />
      <div class="preface__wrapper">
        <p>社工是一群專業的助人工作者，為何飽受社會大眾的誤解？他們面對社會最悲劇的陰暗角落，為何成了憂鬱沮喪的專業人士？</p>
        <p>《鏡週刊》人物組採用台北市社工師公會最新的社工職場問卷普查數據，發現七成以上社工有嚴重心理創傷。我們採訪多位第一線服務社工與前社工，製作專題報導：<a href="https://www.mirrormedia.mg/story/20200424pol001/" target="_blank">《我們不是神：看不見的社工職業創傷》</a>，及心理測驗遊戲：「如果我是社工，我要如何幫助他？」邀你體驗社工日常的助人兩難，看看你屬於哪一種社工？</p>
      </div>
    </div>
  </div>
</template>

<svelte:window bind:innerWidth={ww} />

<script>
import titleMob from '../assets/title-mob.svg'
import titleDesk from '../assets/title-desk.svg'

let ww = 0

$: isDeskW = ww >= 768

</script>
<style lang="scss">
@import '../util/breakpoint.scss';

.the-cover {
  background-color: #1a1a1a;
  min-height: 100vh;
  padding-left: 20px;
  padding-right: 20px;
  position: relative;
  @media (min-width: $breakpoint-md) {
    padding-left: 0;
    padding-right: 0;
  }
}
.bg {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  background-position: center;
  background-size: cover;
  background-repeat: no-repeat;
  &--cover {
    height: 180px;
    background-image: url(../assets/cover-mob.jpg);
    @media (min-width: $breakpoint-md) {
      background-image: url(../assets/cover-desk.jpg);
      height: 100%;
    }
  }
  &--girl {
    display: none;
    @media (min-width: $breakpoint-md) {
      display: block;
      background-image: url(../assets/girl.png);
      height: 100%;
      z-index: 9;
    }
  }
}
.title {
  width: 90px;
  height: auto;
  vertical-align: top;
  padding-top: 14px;
  padding-bottom: 44px;
  position: relative;
  left: 24.36%;
  // right: 29.44%;
  @media (min-width: $breakpoint-md) {
    padding-top: 48px;
    width: 46.32%;
    padding-bottom: 6px;
  }
}
.preface {
  font-size: 1.8rem;
  font-weight: 500;
  line-height: 1.67;
  color: #fff;
  padding-bottom: 40px;
  position: relative;
  @media (min-width: $breakpoint-md) {
    width: 50vw;
    max-width: 720px;
    padding: 45px 4.72vw 60px 12.64vw;
    left: 16.67%;
    box-sizing: border-box;
  }
  &__bg {
    display: none;
    @media (min-width: $breakpoint-md) {
      display: block;
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-color: #1a1a1a;
    }
  }
  &__wrapper {
    position: relative;
    z-index: 19;
    &::before {
      @media (min-width: $breakpoint-md) {
        content: '';
        display: block;
        position: absolute;
        width: 16px;
        height: 16px;
        background-color: #fbcd78;
        border-radius: 50%;
        top: 7px;
        left: -36px;
      }
    }
  }
}
p + p {
  margin-top: 30px;
}
a {
  color: #fbcd78;
  text-decoration: underline;
  cursor: pointer;
}
</style>
